# Generated by Django 4.2.4 on 2023-10-26 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsfields',
            name='c',
        ),
        migrations.RemoveField(
            model_name='skillsfields',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='skillsfields',
            name='j',
        ),
    ]
