# Generated by Django 4.2.4 on 2023-10-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal_api', '0002_remove_skillsfields_c_remove_skillsfields_cp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsfields',
            name='p',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='back_pic',
            field=models.ImageField(default='back_profile.webp', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile_pic.jpg', upload_to='media'),
        ),
    ]
